### ISSUE TITLE
MyDateTime from DateTime<FixedOffset>

### ISSUE THREAD

**Issue by FelixPodint** [duesee/imap-codec#19]
Hi,

Is there a way to create `MyDateTime` from `chrono` `DateTime<FixedOffset>`?
I can see that `MyDateTime` already have `DateTime<FixedOffset>` as its tuple field, but it's public in scope of crate.

Thanks,
Felix P.

**Comment by FelixPodint** [comment]
Is there a reason why this:
```
NString(Some(IString::Literal(Literal::from(
    &LiteralRef::from_bytes(b"NOT WORKING").unwrap(),
))));
```
is better than this:
```
NString(Some(IString::Literal(
    Literal(b"NOT WORKING".to_vec())
)));
```

I think it's the same problem as with `MyDateTime`. Type could be created from simple data, but its fields are not public or there is no .new() method.

**Comment by duesee** [comment]
> Is there a reason why this:
> 
> ```
> NString(Some(IString::Literal(Literal::from(
>     &LiteralRef::from_bytes(b"NOT WORKING").unwrap(),
> ))));
> ```
> 
> is better than this:
> 
> ```
> NString(Some(IString::Literal(
>     Literal(b"NOT WORKING".to_vec())
> )));
> ```
> 
> I think it's the same problem as with `MyDateTime`. Type could be created from simple data, but its fields are not public or there is no .new() method.

Unfortunately, Yes. An IMAP literal does not allow any byte sequence, because 0x00 is forbidden. Thus, when we would allow to do `Literal(b"NOT WORKING".to_vec())`, a user could also do `Literal(b"\x00".to_vec())`, which would result in an invalid IMAP message. This is one guarantee that imap-codec should make: never ever produce invalid messages.

However, the API is not finished, which is why you find such awkward constructs. In the long run I would want to provide builders or simply `Literal::try_from(b"Foo").unwrap()`.

**Comment by duesee** [comment]
Regarding `MyDate`: `MyDate` should likely not exist in this form, but I am not 100% sure why I introduced it in the first place :-/ `chrono` is AFAIK not maintained anymore and should be replaced with `time`, see #10. Feel free to make any change that suits you, as long as it doesn't break the correctness guarantee.

**Comment by FelixPodint** [comment]
Oh ok.
I did this for myself:
```
pub struct MyDateTime(pub DateTime<FixedOffset>);
```
It will suffice for now.
Don't think PR is needed for this case.
