### ISSUE TITLE
question/refactor: Simplify `MaxMessageSize`?

### ISSUE THREAD

**Issue by duesee** [duesee/imap-codec#541]
See https://github.com/duesee/imap-codec/pull/540#discussion_r1676798782

**Comment by jakoschiko** [comment]
In `imap-next` we use `u32` for limits and 0 does mean 0. If you want no limit, then `u32::MAX` is the best you can get. I did it because IMAP defines the length of a literal as 4-byte integer. So using `u32` as the literal limit felt like an obvious decision. The other limits are `u32` for consistency reasons.

I mention it because it would be nice if we would use the same representation in `imap-codec` and `imap-next`.

**Comment by duesee** [comment]
Yeah. I don't like 0 as "unlimited" tbh. It seems like a hack for me and we have a better `Option<u32>` :-)

**Comment by jakoschiko** [comment]
@duesee: Closed?
